apiVersion: v1
kind: ConfigMap
metadata:
  name: cilist-be-configmap
  namespace: devops-ariandy
data:
  BASE_URL_PORT : "5000"
  DATABASE_USERNAME : "people"
  DATABASE_PASSWORD : "s3k0l4hd3v0p5"
  DATABASE_DATABASE : "people"
  DATABASE_HOST : "ariandy-db-instance.c8bo20yarupg.us-west-2.rds.amazonaws.com"
  DATABASE_PORT : "3306"

---

apiVersion: v1
kind: Service
metadata:
  name: cilist-be-service
  namespace: devops-ariandy
spec:
  selector:
    app: cilist
    tier: backend
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30001
    port: 5000
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilist-be
  namespace: devops-ariandy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cilist
      tier: backend
  template:
    metadata:
      labels:
        app: cilist
        tier: backend
    spec:
      containers:
      - name: cilist-be-container
        image: ooxyz/x-be:latest
        ports:
        - containerPort: 5000
        env:
        - name: BASE_URL_PORT
          valueFrom:
            configMapKeyRef:
              name: cilist-be-configmap
              key: BASE_URL_PORT
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: cilist-be-configmap
              key: DATABASE_PORT
        - name: DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: cilist-be-configmap
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: cilist-be-configmap
              key: DATABASE_PASSWORD
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: cilist-be-configmap
              key: DATABASE_HOST
        - name: DATABASE_DATABASE
          valueFrom:
            configMapKeyRef:
              name: cilist-be-configmap
              key: DATABASE_DATABASE

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: devops-ariandy
  name: cilist-ingress-be
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: kube.ariandy.com
      http:
        paths:
        - path: /be(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: cilist-be-service
              port:
                number: 5000