apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: {{ .Values.secret.type }}
data:
  DATABASE_USERNAME: {{ .Values.secret.data.username }}
  DATABASE_PASSWORD: {{ .Values.secret.data.password }}