apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name.be }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.label.app }}
    tier: {{ .Values.label.tier.be }}
  ports:
  - protocol: {{ .Values.service.protocol }}
    port: {{ .Values.port.be }}
    targetPort: {{ .Values.port.be }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name.fe }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.label.app }}
    tier: {{ .Values.label.tier.fe }}
  ports:
  - protocol: {{ .Values.service.protocol }}
    port: {{ .Values.port.fe }}
    targetPort: {{ .Values.port.fe }}